Add support for the recognition of the mvapich2 mpi implementation and also make offline the default instrumentor if no instrumentor is set using the --with-instrumentor phrase.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -944,6 +944,14 @@ MVAPICH_LDFLAGS
 MVAPICH_LIBS
 MVAPICH_HEADER
 MVAPICH_DIR
+HAVE_MVAPICH2_TRUE
+HAVE_MVAPICH2_FALSE
+MVAPICH2_CC
+MVAPICH2_CPPFLAGS
+MVAPICH2_LDFLAGS
+MVAPICH2_LIBS
+MVAPICH2_HEADER
+MVAPICH2_DIR
 HAVE_MPT_TRUE
 HAVE_MPT_FALSE
 MPT_CC
@@ -1672,6 +1680,7 @@ Optional Packages:
                           MPICH driver name [ch-p4]
   --with-mpich2=DIR       MPICH2 installation [/opt/mpich2]
   --with-mvapich=DIR      MVAPICH installation [/opt/mvapich]
+  --with-mvapich2=DIR     MVAPICH2 installation [/opt/mvapich2]
   --with-mpt=DIR          MPT installation [/usr]
   --with-openmpi=DIR      OpenMPI installation [/usr/local]
   --with-otf=DIR          OTF Open Trace Format library installation [/usr]
@@ -1683,7 +1692,8 @@ Optional Packages:
   --with-python=PYTHON    path name of Python libraries
   --with-libmonitor=DIR   libmonitor installation [/usr]
   --with-instrumentor=TYPE
-                          instrumentor (dpcl, dyninst, mrnet, offline) [dpcl]
+                          instrumentor (dpcl, dyninst, mrnet, offline)
+                          [offline]
   --with-dyninst=DIR      Dyninst installation [/usr]
   --with-dpcl=DIR         DPCL installation [/usr]
   --with-qtlib=DIR        QTLIB installation [/usr]
@@ -5631,7 +5641,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5634 "configure"' > conftest.$ac_ext
+  echo '#line 5644 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7637,11 +7647,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7640: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7650: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7644: \$? = $ac_status" >&5
+   echo "$as_me:7654: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7927,11 +7937,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7930: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7940: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7934: \$? = $ac_status" >&5
+   echo "$as_me:7944: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8031,11 +8041,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8034: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8044: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8038: \$? = $ac_status" >&5
+   echo "$as_me:8048: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10382,7 +10392,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10385 "configure"
+#line 10395 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10482,7 +10492,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10485 "configure"
+#line 10495 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12902,11 +12912,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12905: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12915: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12909: \$? = $ac_status" >&5
+   echo "$as_me:12919: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13006,11 +13016,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13009: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13019: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13013: \$? = $ac_status" >&5
+   echo "$as_me:13023: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14570,11 +14580,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14573: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14583: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14577: \$? = $ac_status" >&5
+   echo "$as_me:14587: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14674,11 +14684,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14677: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14687: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14681: \$? = $ac_status" >&5
+   echo "$as_me:14691: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16863,11 +16873,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16866: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16876: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16870: \$? = $ac_status" >&5
+   echo "$as_me:16880: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17153,11 +17163,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17156: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17166: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17160: \$? = $ac_status" >&5
+   echo "$as_me:17170: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17257,11 +17267,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17260: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17270: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17264: \$? = $ac_status" >&5
+   echo "$as_me:17274: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -22322,6 +22332,150 @@ fi
 
 
 
+# Check whether --with-mvapich2 was given.
+if test "${with_mvapich2+set}" = set; then
+  withval=$with_mvapich2; mvapich2_dir=$withval
+else
+  mvapich2_dir="/opt/mvapich2"
+fi
+
+
+#    AC_ARG_WITH(mvapich2-driver,
+#		AC_HELP_STRING([--with-mvapich2-driver=NAME],
+#			       [MVAPICH2 driver name [ch-p4]]),
+#		mvapich2_driver=$withval, mvapich2_driver="")
+
+    { echo "$as_me:$LINENO: checking for MVAPICH2 library and headers" >&5
+echo $ECHO_N "checking for MVAPICH2 library and headers... $ECHO_C" >&6; }
+
+    found_mvapich2=0
+
+    # Put -shlib into MVAPICH2_CC, since it is needed when building the
+    # tests, where $MVAPICH2_CC is used, and is not needed when building
+    # the MPI-related plugins, where $MVAPICH2_CC is not used.
+    MVAPICH2_CC="$mvapich2_dir/bin/mpicc -shlib"
+    MVAPICH2_CPPFLAGS="-I$mvapich2_dir/include"
+    MVAPICH2_LDFLAGS="-L$mvapich2_dir/$abi_libdir -L$mvapich2_dir/$alt_abi_libdir"
+    MVAPICH2_LIBS="-lmpich -libverbs"
+    MVAPICH2_HEADER="$mvapich2_dir/include/mpi.h"
+    MVAPICH2_DIR="$mvapich2_dir"
+
+    # On the systems "mcr" and "thunder" at LLNL they have an MPICH variant
+    # that has things moved around a bit. Handle this by allowing a "llnl"
+    # pseudo-driver that makes the necessary configuration changes.
+#    if test x"$mvapich2_driver" == x"llnl"; then
+#	MVAPICH2_CC="$mvapich2_dir/bin/mpicc -shlib"
+#        MVAPICH2_LDFLAGS="-L$mvapich2_dir/$abi_libdir"
+#    fi
+
+    mvapich2_saved_CC=$CC
+    mvapich2_saved_CPPFLAGS=$CPPFLAGS
+    mvapich2_saved_LDFLAGS=$LDFLAGS
+
+    CC="$MVAPICH2_CC"
+    CPPFLAGS="$CPPFLAGS $MVAPICH2_CPPFLAGS"
+    LDFLAGS="$LDFLAGS $MVAPICH2_LIBS $MVAPICH2_LDFLAGS $MVAPICH2_LIBS"
+
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+	#include <mpi.h>
+
+int
+main ()
+{
+
+	MPI_Initialized((int*)0);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  found_mvapich=1
+
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+
+    CC=$mvapich2_saved_CC
+    CPPFLAGS=$mvapich2_saved_CPPFLAGS
+    LDFLAGS=$mvapich2_saved_LDFLAGS
+
+    if test $found_mvapich -eq 1; then
+	{ echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+	 if true; then
+  HAVE_MVAPICH2_TRUE=
+  HAVE_MVAPICH2_FALSE='#'
+else
+  HAVE_MVAPICH2_TRUE='#'
+  HAVE_MVAPICH2_FALSE=
+fi
+
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_MVAPICH2 1
+_ACEOF
+
+    else
+	{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+	 if false; then
+  HAVE_MVAPICH2_TRUE=
+  HAVE_MVAPICH2_FALSE='#'
+else
+  HAVE_MVAPICH2_TRUE='#'
+  HAVE_MVAPICH2_FALSE=
+fi
+
+	MVAPICH2_CC=""
+	MVAPICH2_CPPFLAGS=""
+	MVAPICH2_LDFLAGS=""
+	MVAPICH2_LIBS=""
+	MVAPICH2_HEADER=""
+	MVAPICH2_DIR=""
+    fi
+
+
+
+
+
+
+
+
+
+
+
+
 # Check whether --with-mpt was given.
 if test "${with_mpt+set}" = set; then
   withval=$with_mpt; mpt_dir=$withval
@@ -22878,6 +23032,10 @@ fi
     if test x"$MVAPICH_LDFLAGS" != x""; then
 	default_mpi=MVAPICH;    default_mpi_name=mvapich
 	all_mpi_names=" mvapich $all_mpi_names"
+    fi
+    if test x"$MVAPICH2_LDFLAGS" != x""; then
+	default_mpi=MVAPICH2;    default_mpi_name=mvapich2
+	all_mpi_names=" mvapich2 $all_mpi_names"
     fi
 
     if test x"$default_mpi" != x""; then
@@ -24000,7 +24158,7 @@ rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
 if test "${with_instrumentor+set}" = set; then
   withval=$with_instrumentor; INSTRUMENTOR=$withval
 else
-  INSTRUMENTOR="dpcl"
+  INSTRUMENTOR="offline"
 fi
 
 
@@ -27817,6 +27975,20 @@ echo "$as_me: error: conditional \"HAVE_MVAPICH\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${HAVE_MVAPICH2_TRUE}" && test -z "${HAVE_MVAPICH2_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_MVAPICH2\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_MVAPICH2\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HAVE_MVAPICH2_TRUE}" && test -z "${HAVE_MVAPICH2_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_MVAPICH2\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_MVAPICH2\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${HAVE_MPT_TRUE}" && test -z "${HAVE_MPT_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"HAVE_MPT\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -29076,6 +29248,14 @@ MVAPICH_LDFLAGS!$MVAPICH_LDFLAGS$ac_delim
 MVAPICH_LIBS!$MVAPICH_LIBS$ac_delim
 MVAPICH_HEADER!$MVAPICH_HEADER$ac_delim
 MVAPICH_DIR!$MVAPICH_DIR$ac_delim
+HAVE_MVAPICH2_TRUE!$HAVE_MVAPICH2_TRUE$ac_delim
+HAVE_MVAPICH2_FALSE!$HAVE_MVAPICH2_FALSE$ac_delim
+MVAPICH2_CC!$MVAPICH2_CC$ac_delim
+MVAPICH2_CPPFLAGS!$MVAPICH2_CPPFLAGS$ac_delim
+MVAPICH2_LDFLAGS!$MVAPICH2_LDFLAGS$ac_delim
+MVAPICH2_LIBS!$MVAPICH2_LIBS$ac_delim
+MVAPICH2_HEADER!$MVAPICH2_HEADER$ac_delim
+MVAPICH2_DIR!$MVAPICH2_DIR$ac_delim
 HAVE_MPT_TRUE!$HAVE_MPT_TRUE$ac_delim
 HAVE_MPT_FALSE!$HAVE_MPT_FALSE$ac_delim
 MPT_CC!$MPT_CC$ac_delim
@@ -29086,14 +29266,6 @@ MPT_HEADER!$MPT_HEADER$ac_delim
 MPT_DIR!$MPT_DIR$ac_delim
 HAVE_OPENMPI_TRUE!$HAVE_OPENMPI_TRUE$ac_delim
 HAVE_OPENMPI_FALSE!$HAVE_OPENMPI_FALSE$ac_delim
-OPENMPI_CC!$OPENMPI_CC$ac_delim
-OPENMPI_CPPFLAGS!$OPENMPI_CPPFLAGS$ac_delim
-OPENMPI_LDFLAGS!$OPENMPI_LDFLAGS$ac_delim
-OPENMPI_LIBS!$OPENMPI_LIBS$ac_delim
-OPENMPI_HEADER!$OPENMPI_HEADER$ac_delim
-OPENMPI_DIR!$OPENMPI_DIR$ac_delim
-HAVE_MPI_TRUE!$HAVE_MPI_TRUE$ac_delim
-HAVE_MPI_FALSE!$HAVE_MPI_FALSE$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -29135,6 +29307,14 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+OPENMPI_CC!$OPENMPI_CC$ac_delim
+OPENMPI_CPPFLAGS!$OPENMPI_CPPFLAGS$ac_delim
+OPENMPI_LDFLAGS!$OPENMPI_LDFLAGS$ac_delim
+OPENMPI_LIBS!$OPENMPI_LIBS$ac_delim
+OPENMPI_HEADER!$OPENMPI_HEADER$ac_delim
+OPENMPI_DIR!$OPENMPI_DIR$ac_delim
+HAVE_MPI_TRUE!$HAVE_MPI_TRUE$ac_delim
+HAVE_MPI_FALSE!$HAVE_MPI_FALSE$ac_delim
 DEFAULT_MPI_IMPL!$DEFAULT_MPI_IMPL$ac_delim
 HAVE_OPENMP_TRUE!$HAVE_OPENMP_TRUE$ac_delim
 HAVE_OPENMP_FALSE!$HAVE_OPENMP_FALSE$ac_delim
@@ -29216,7 +29396,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 79; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 87; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
diff --git a/test/executables/configure b/test/executables/configure
--- a/test/executables/configure
+++ b/test/executables/configure
@@ -912,6 +912,14 @@ MVAPICH_LDFLAGS
 MVAPICH_LIBS
 MVAPICH_HEADER
 MVAPICH_DIR
+HAVE_MVAPICH2_TRUE
+HAVE_MVAPICH2_FALSE
+MVAPICH2_CC
+MVAPICH2_CPPFLAGS
+MVAPICH2_LDFLAGS
+MVAPICH2_LIBS
+MVAPICH2_HEADER
+MVAPICH2_DIR
 HAVE_MPT_TRUE
 HAVE_MPT_FALSE
 MPT_CC
@@ -1550,6 +1558,7 @@ Optional Packages:
                           MPICH driver name [ch-p4]
   --with-mpich2=DIR       MPICH2 installation [/opt/mpich2]
   --with-mvapich=DIR      MVAPICH installation [/opt/mvapich]
+  --with-mvapich2=DIR     MVAPICH2 installation [/opt/mvapich2]
   --with-mpt=DIR          MPT installation [/usr]
   --with-openmpi=DIR      OpenMPI installation [/usr/local]
 
@@ -4858,7 +4867,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4861 "configure"' > conftest.$ac_ext
+  echo '#line 4870 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7124,11 +7133,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7127: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7136: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7131: \$? = $ac_status" >&5
+   echo "$as_me:7140: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7414,11 +7423,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7417: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7426: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7421: \$? = $ac_status" >&5
+   echo "$as_me:7430: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7518,11 +7527,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7521: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7530: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7525: \$? = $ac_status" >&5
+   echo "$as_me:7534: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9869,7 +9878,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9872 "configure"
+#line 9881 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9969,7 +9978,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9972 "configure"
+#line 9981 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12389,11 +12398,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12392: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12401: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12396: \$? = $ac_status" >&5
+   echo "$as_me:12405: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12493,11 +12502,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12496: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12505: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12500: \$? = $ac_status" >&5
+   echo "$as_me:12509: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14057,11 +14066,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14060: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14069: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14064: \$? = $ac_status" >&5
+   echo "$as_me:14073: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14161,11 +14170,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14164: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14173: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14168: \$? = $ac_status" >&5
+   echo "$as_me:14177: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16350,11 +16359,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16353: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16362: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16357: \$? = $ac_status" >&5
+   echo "$as_me:16366: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16640,11 +16649,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16643: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16652: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16647: \$? = $ac_status" >&5
+   echo "$as_me:16656: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16744,11 +16753,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16747: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16756: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16751: \$? = $ac_status" >&5
+   echo "$as_me:16760: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -20823,6 +20832,150 @@ fi
 
 
 
+# Check whether --with-mvapich2 was given.
+if test "${with_mvapich2+set}" = set; then
+  withval=$with_mvapich2; mvapich2_dir=$withval
+else
+  mvapich2_dir="/opt/mvapich2"
+fi
+
+
+#    AC_ARG_WITH(mvapich2-driver,
+#		AC_HELP_STRING([--with-mvapich2-driver=NAME],
+#			       [MVAPICH2 driver name [ch-p4]]),
+#		mvapich2_driver=$withval, mvapich2_driver="")
+
+    { echo "$as_me:$LINENO: checking for MVAPICH2 library and headers" >&5
+echo $ECHO_N "checking for MVAPICH2 library and headers... $ECHO_C" >&6; }
+
+    found_mvapich2=0
+
+    # Put -shlib into MVAPICH2_CC, since it is needed when building the
+    # tests, where $MVAPICH2_CC is used, and is not needed when building
+    # the MPI-related plugins, where $MVAPICH2_CC is not used.
+    MVAPICH2_CC="$mvapich2_dir/bin/mpicc -shlib"
+    MVAPICH2_CPPFLAGS="-I$mvapich2_dir/include"
+    MVAPICH2_LDFLAGS="-L$mvapich2_dir/$abi_libdir -L$mvapich2_dir/$alt_abi_libdir"
+    MVAPICH2_LIBS="-lmpich -libverbs"
+    MVAPICH2_HEADER="$mvapich2_dir/include/mpi.h"
+    MVAPICH2_DIR="$mvapich2_dir"
+
+    # On the systems "mcr" and "thunder" at LLNL they have an MPICH variant
+    # that has things moved around a bit. Handle this by allowing a "llnl"
+    # pseudo-driver that makes the necessary configuration changes.
+#    if test x"$mvapich2_driver" == x"llnl"; then
+#	MVAPICH2_CC="$mvapich2_dir/bin/mpicc -shlib"
+#        MVAPICH2_LDFLAGS="-L$mvapich2_dir/$abi_libdir"
+#    fi
+
+    mvapich2_saved_CC=$CC
+    mvapich2_saved_CPPFLAGS=$CPPFLAGS
+    mvapich2_saved_LDFLAGS=$LDFLAGS
+
+    CC="$MVAPICH2_CC"
+    CPPFLAGS="$CPPFLAGS $MVAPICH2_CPPFLAGS"
+    LDFLAGS="$LDFLAGS $MVAPICH2_LIBS $MVAPICH2_LDFLAGS $MVAPICH2_LIBS"
+
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+	#include <mpi.h>
+
+int
+main ()
+{
+
+	MPI_Initialized((int*)0);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  found_mvapich=1
+
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+
+    CC=$mvapich2_saved_CC
+    CPPFLAGS=$mvapich2_saved_CPPFLAGS
+    LDFLAGS=$mvapich2_saved_LDFLAGS
+
+    if test $found_mvapich -eq 1; then
+	{ echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+	 if true; then
+  HAVE_MVAPICH2_TRUE=
+  HAVE_MVAPICH2_FALSE='#'
+else
+  HAVE_MVAPICH2_TRUE='#'
+  HAVE_MVAPICH2_FALSE=
+fi
+
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_MVAPICH2 1
+_ACEOF
+
+    else
+	{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+	 if false; then
+  HAVE_MVAPICH2_TRUE=
+  HAVE_MVAPICH2_FALSE='#'
+else
+  HAVE_MVAPICH2_TRUE='#'
+  HAVE_MVAPICH2_FALSE=
+fi
+
+	MVAPICH2_CC=""
+	MVAPICH2_CPPFLAGS=""
+	MVAPICH2_LDFLAGS=""
+	MVAPICH2_LIBS=""
+	MVAPICH2_HEADER=""
+	MVAPICH2_DIR=""
+    fi
+
+
+
+
+
+
+
+
+
+
+
+
 # Check whether --with-mpt was given.
 if test "${with_mpt+set}" = set; then
   withval=$with_mpt; mpt_dir=$withval
@@ -21380,6 +21533,10 @@ fi
 	default_mpi=MVAPICH;    default_mpi_name=mvapich
 	all_mpi_names=" mvapich $all_mpi_names"
     fi
+    if test x"$MVAPICH2_LDFLAGS" != x""; then
+	default_mpi=MVAPICH2;    default_mpi_name=mvapich2
+	all_mpi_names=" mvapich2 $all_mpi_names"
+    fi
 
     if test x"$default_mpi" != x""; then
 	 if true; then
@@ -21683,6 +21840,20 @@ if test -z "${HAVE_MVAPICH_TRUE}" && test -z "${HAVE_MVAPICH_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"HAVE_MVAPICH\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"HAVE_MVAPICH\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HAVE_MVAPICH2_TRUE}" && test -z "${HAVE_MVAPICH2_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_MVAPICH2\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_MVAPICH2\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HAVE_MVAPICH2_TRUE}" && test -z "${HAVE_MVAPICH2_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_MVAPICH2\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_MVAPICH2\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -22443,6 +22614,14 @@ MVAPICH_LDFLAGS!$MVAPICH_LDFLAGS$ac_delim
 MVAPICH_LIBS!$MVAPICH_LIBS$ac_delim
 MVAPICH_HEADER!$MVAPICH_HEADER$ac_delim
 MVAPICH_DIR!$MVAPICH_DIR$ac_delim
+HAVE_MVAPICH2_TRUE!$HAVE_MVAPICH2_TRUE$ac_delim
+HAVE_MVAPICH2_FALSE!$HAVE_MVAPICH2_FALSE$ac_delim
+MVAPICH2_CC!$MVAPICH2_CC$ac_delim
+MVAPICH2_CPPFLAGS!$MVAPICH2_CPPFLAGS$ac_delim
+MVAPICH2_LDFLAGS!$MVAPICH2_LDFLAGS$ac_delim
+MVAPICH2_LIBS!$MVAPICH2_LIBS$ac_delim
+MVAPICH2_HEADER!$MVAPICH2_HEADER$ac_delim
+MVAPICH2_DIR!$MVAPICH2_DIR$ac_delim
 HAVE_MPT_TRUE!$HAVE_MPT_TRUE$ac_delim
 HAVE_MPT_FALSE!$HAVE_MPT_FALSE$ac_delim
 MPT_CC!$MPT_CC$ac_delim
@@ -22466,7 +22645,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 68; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 76; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
