Help an issue with mvapich2 configuration found on yellowrail by Sam.  Added a --with-mvapich2-ofed= so that the full open fabric library set can be pointed to in /opt/ofed on yr.  The install.sh and openspeedshop-1.9.2_a.spec files have been updated to take the OPENSS_OFED environment variable which can be set to /opt/ofed, it defaults to /usr.  There were also issues in the mpich2, mvapich and mvapich2 configuration code in ac_pkg_mpi.m4.  This should be improved by these changes.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1682,6 +1682,8 @@ Optional Packages:
   --with-mpich2=DIR       MPICH2 installation [/opt/mpich2]
   --with-mvapich=DIR      MVAPICH installation [/opt/mvapich]
   --with-mvapich2=DIR     MVAPICH2 installation [/opt/mvapich2]
+  --with-mvapich2-ofed=DIR
+                          MVAPICH2 open fabrics installation dir [/usr]
   --with-mpt=DIR          MPT installation [/usr]
   --with-openmpi=DIR      OpenMPI installation [/usr/local]
   --with-otf=DIR          OTF Open Trace Format library installation [/usr]
@@ -5642,7 +5644,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5645 "configure"' > conftest.$ac_ext
+  echo '#line 5647 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7648,11 +7650,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7651: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7653: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7655: \$? = $ac_status" >&5
+   echo "$as_me:7657: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7938,11 +7940,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7941: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7943: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7945: \$? = $ac_status" >&5
+   echo "$as_me:7947: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8042,11 +8044,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8045: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8047: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8049: \$? = $ac_status" >&5
+   echo "$as_me:8051: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10393,7 +10395,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10396 "configure"
+#line 10398 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10493,7 +10495,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10496 "configure"
+#line 10498 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12913,11 +12915,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12916: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12918: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12920: \$? = $ac_status" >&5
+   echo "$as_me:12922: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13017,11 +13019,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13020: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13022: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13024: \$? = $ac_status" >&5
+   echo "$as_me:13026: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14581,11 +14583,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14584: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14586: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14588: \$? = $ac_status" >&5
+   echo "$as_me:14590: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14685,11 +14687,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14688: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14690: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14692: \$? = $ac_status" >&5
+   echo "$as_me:14694: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16874,11 +16876,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16877: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16879: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16881: \$? = $ac_status" >&5
+   echo "$as_me:16883: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17164,11 +17166,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17167: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17169: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17171: \$? = $ac_status" >&5
+   echo "$as_me:17173: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17268,11 +17270,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17271: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17273: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17275: \$? = $ac_status" >&5
+   echo "$as_me:17277: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -22067,7 +22069,7 @@ echo $ECHO_N "checking for MPICH2 library and headers... $ECHO_C" >&6; }
     MPICH2_CC="$mpich2_dir/bin/mpicc"
 #    MPICH2_CC="$mpich2_dir/bin/mpicc -shlib"
     MPICH2_CPPFLAGS="-I$mpich2_dir/include"
-    MPICH2_LDFLAGS="-L$mpich2_dir/$abi_libdir -L$mpich2_dir/$alt_abi_libdir/libmpich.a"
+    MPICH2_LDFLAGS="-L$mpich2_dir/$abi_libdir -L$mpich2_dir/$abi_libdir/libmpich.a"
 #    MPICH2_LIBS="-lmpich"
     MPICH2_LIBS=""
     MPICH2_HEADER="$mpich2_dir/include/mpi.h"
@@ -22126,7 +22128,10 @@ eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
 	 test ! -s conftest.err
        } && test -s conftest$ac_exeext &&
        $as_test_x conftest$ac_exeext; then
-  found_mpich2=1
+  if ( (test -f $mpich2_dir/$abi_libdir/libmpich.a) ||
+             (test -f $mpich2_dir/$abi_libdir/shared/libmpich.so) ) ; then
+	    found_mpich2=1
+        fi
 
 
 else
@@ -22138,6 +22143,82 @@ fi
 
 rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
       conftest$ac_exeext conftest.$ac_ext
+
+    if test $found_mpich2 -eq 0; then
+
+       { echo "$as_me:$LINENO: checking for MPICH2 library (alt locations) and headers" >&5
+echo $ECHO_N "checking for MPICH2 library (alt locations) and headers... $ECHO_C" >&6; }
+
+       # Put -shlib into MPICH2_CC, since it is needed when building the
+       # tests, where $MPICH2_CC is used, and is not needed when building
+       # the MPI-related plugins, where $MPICH2_CC is not used.
+       MPICH2_CC="$mpich2_dir/bin/mpicc"
+#       MPICH2_CC="$mpich2_dir/bin/mpicc -shlib"
+       MPICH2_CPPFLAGS="-I$mpich2_dir/include"
+       MPICH2_LDFLAGS="-L$mpich2_dir/$alt_abi_libdir -L$mpich2_dir/$alt_abi_libdir/libmpich.a"
+#       MPICH2_LIBS="-lmpich"
+       MPICH2_LIBS=""
+       MPICH2_HEADER="$mpich2_dir/include/mpi.h"
+       MPICH2_DIR="$mpich2_dir"
+
+       CC="$MPICH2_CC"
+       CPPFLAGS="$CPPFLAGS $MPICH2_CPPFLAGS"
+       LDFLAGS="$LDFLAGS $MPICH2_LDFLAGS $MPICH_LIBS"
+
+       cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+   	  #include <mpi.h>
+
+int
+main ()
+{
+
+	  MPI_Initialized((int*)0);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  if ( (test -f $mpich2_dir/$alt_abi_libdir/libmpich.a) ||
+              (test -f $mpich2_dir/$alt_abi_libdir/shared/libmpich.so) ) ; then
+	     found_mpich2=1
+         fi
+
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+
+    fi
 
     CC=$mpich2_saved_CC
     CPPFLAGS=$mpich2_saved_CPPFLAGS
@@ -22212,7 +22293,7 @@ echo $ECHO_N "checking for MVAPICH library and headers... $ECHO_C" >&6; }
     # the MPI-related plugins, where $MVAPICH_CC is not used.
     MVAPICH_CC="$mvapich_dir/bin/mpicc -shlib"
     MVAPICH_CPPFLAGS="-I$mvapich_dir/include"
-    MVAPICH_LDFLAGS="-L$mvapich_dir/$abi_libdir -L$mvapich_dir/$alt_abi_libdir"
+    MVAPICH_LDFLAGS="-L$mvapich_dir/$abi_libdir"
     MVAPICH_LIBS="-lmpich -libverbs"
     MVAPICH_HEADER="$mvapich_dir/include/mpi.h"
     MVAPICH_DIR="$mvapich_dir"
@@ -22270,7 +22351,10 @@ eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
 	 test ! -s conftest.err
        } && test -s conftest$ac_exeext &&
        $as_test_x conftest$ac_exeext; then
-  found_mvapich=1
+  if ( (test -f $mvapich_dir/$abi_libdir/libmpich.a) ||
+             (test -f $mvapich_dir/$abi_libdir/shared/libmpich.so) ) ; then
+            found_mvapich=1
+        fi
 
 
 else
@@ -22282,6 +22366,79 @@ fi
 
 rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
       conftest$ac_exeext conftest.$ac_ext
+
+    if test $found_mvapich -eq 0; then
+       { echo "$as_me:$LINENO: checking for MVAPICH library (alt locations) and headers" >&5
+echo $ECHO_N "checking for MVAPICH library (alt locations) and headers... $ECHO_C" >&6; }
+
+       # Put -shlib into MVAPICH_CC, since it is needed when building the
+       # tests, where $MVAPICH_CC is used, and is not needed when building
+       # the MPI-related plugins, where $MVAPICH_CC is not used.
+       MVAPICH_CC="$mvapich_dir/bin/mpicc -shlib"
+       MVAPICH_CPPFLAGS="-I$mvapich_dir/include"
+       MVAPICH_LDFLAGS="-L$mvapich_dir/$alt_abi_libdir"
+       MVAPICH_LIBS="-lmpich -libverbs"
+       MVAPICH_HEADER="$mvapich_dir/include/mpi.h"
+       MVAPICH_DIR="$mvapich_dir"
+
+       CC="$MVAPICH_CC"
+       CPPFLAGS="$CPPFLAGS $MVAPICH_CPPFLAGS"
+       LDFLAGS="$LDFLAGS $MVAPICH_LIBS $MVAPICH_LDFLAGS $MVAPICH_LIBS"
+
+       cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+   	  #include <mpi.h>
+
+int
+main ()
+{
+
+	  MPI_Initialized((int*)0);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  if ( (test -f $mvapich_dir/$alt_abi_libdir/libmpich.a) ||
+              (test -f $mvapich_dir/$alt_abi_libdir/shared/libmpich.so) ) ; then
+	     found_mvapich=1
+         fi
+
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+
+    fi
 
     CC=$mvapich_saved_CC
     CPPFLAGS=$mvapich_saved_CPPFLAGS
@@ -22341,10 +22498,14 @@ else
 fi
 
 
-#    AC_ARG_WITH(mvapich2-driver,
-#		AC_HELP_STRING([--with-mvapich2-driver=NAME],
-#			       [MVAPICH2 driver name [ch-p4]]),
-#		mvapich2_driver=$withval, mvapich2_driver="")
+
+# Check whether --with-mvapich2-ofed was given.
+if test "${with_mvapich2_ofed+set}" = set; then
+  withval=$with_mvapich2_ofed; mvapich2_ofed_dir=$withval
+else
+  mvapich2_ofed_dir="/usr"
+fi
+
 
     { echo "$as_me:$LINENO: checking for MVAPICH2 library and headers" >&5
 echo $ECHO_N "checking for MVAPICH2 library and headers... $ECHO_C" >&6; }
@@ -22356,7 +22517,7 @@ echo $ECHO_N "checking for MVAPICH2 library and headers... $ECHO_C" >&6; }
     # the MPI-related plugins, where $MVAPICH2_CC is not used.
     MVAPICH2_CC="$mvapich2_dir/bin/mpicc -shlib"
     MVAPICH2_CPPFLAGS="-I$mvapich2_dir/include"
-    MVAPICH2_LDFLAGS="-L$mvapich2_dir/$abi_libdir -L$mvapich2_dir/$alt_abi_libdir"
+    MVAPICH2_LDFLAGS="-L$mvapich2_dir/$abi_libdir -L$mvapich2_ofed_dir/$abi_libdir"
     MVAPICH2_LIBS="-lmpich -libverbs -libcommon"
     MVAPICH2_HEADER="$mvapich2_dir/include/mpi.h"
     MVAPICH2_DIR="$mvapich2_dir"
@@ -22415,7 +22576,10 @@ eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
 	 test ! -s conftest.err
        } && test -s conftest$ac_exeext &&
        $as_test_x conftest$ac_exeext; then
-  found_mvapich2=1
+  if ( (test -f $mvapich2_dir/$abi_libdir/libmpich.a) ||
+             (test -f $mvapich2_dir/$abi_libdir/shared/libmpich.so) ) ; then
+	    found_mvapich2=1
+        fi
 
 
 else
@@ -22427,6 +22591,81 @@ fi
 
 rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
       conftest$ac_exeext conftest.$ac_ext
+
+    if test $found_mvapich2 -eq 0; then
+
+       { echo "$as_me:$LINENO: checking for MVAPICH2 library (alt locations) and headers" >&5
+echo $ECHO_N "checking for MVAPICH2 library (alt locations) and headers... $ECHO_C" >&6; }
+
+       # Put -shlib into MVAPICH2_CC, since it is needed when building the
+       # tests, where $MVAPICH2_CC is used, and is not needed when building
+       # the MPI-related plugins, where $MVAPICH2_CC is not used.
+       MVAPICH2_CC="$mvapich2_dir/bin/mpicc -shlib"
+       MVAPICH2_CPPFLAGS="-I$mvapich2_dir/include"
+       MVAPICH2_LDFLAGS="-L$mvapich2_dir/$alt_abi_libdir -L$mvapich2_ofed_dir/$alt_abi_libdir"
+       MVAPICH2_LIBS="-lmpich -libverbs -libcommon"
+       MVAPICH2_HEADER="$mvapich2_dir/include/mpi.h"
+       MVAPICH2_DIR="$mvapich2_dir"
+       MVAPICH2_NULL=""
+
+       CC="$MVAPICH2_CC"
+       CPPFLAGS="$CPPFLAGS $MVAPICH2_CPPFLAGS"
+       LDFLAGS="$LDFLAGS $MVAPICH2_LIBS $MVAPICH2_LDFLAGS $MVAPICH2_LIBS"
+
+       cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+   	  #include <mpi.h>
+
+int
+main ()
+{
+
+	  MPI_Initialized((int*)0);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  if ( (test -f $mvapich2_dir/$alt_abi_libdir/libmpich.a) ||
+               (test -f $mvapich2_dir/$alt_abi_libdir/shared/libmpich.so) ) ; then
+	    found_mvapich2=1
+          fi
+
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+
+    fi
 
     CC=$mvapich2_saved_CC
     CPPFLAGS=$mvapich2_saved_CPPFLAGS
diff --git a/test/executables/configure b/test/executables/configure
--- a/test/executables/configure
+++ b/test/executables/configure
@@ -1560,6 +1560,8 @@ Optional Packages:
   --with-mpich2=DIR       MPICH2 installation [/opt/mpich2]
   --with-mvapich=DIR      MVAPICH installation [/opt/mvapich]
   --with-mvapich2=DIR     MVAPICH2 installation [/opt/mvapich2]
+  --with-mvapich2-ofed=DIR
+                          MVAPICH2 open fabrics installation dir [/usr]
   --with-mpt=DIR          MPT installation [/usr]
   --with-openmpi=DIR      OpenMPI installation [/usr/local]
 
@@ -4868,7 +4870,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4871 "configure"' > conftest.$ac_ext
+  echo '#line 4873 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7134,11 +7136,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7137: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7139: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7141: \$? = $ac_status" >&5
+   echo "$as_me:7143: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7424,11 +7426,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7427: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7429: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7431: \$? = $ac_status" >&5
+   echo "$as_me:7433: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7528,11 +7530,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7531: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7533: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7535: \$? = $ac_status" >&5
+   echo "$as_me:7537: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9879,7 +9881,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9882 "configure"
+#line 9884 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9979,7 +9981,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9982 "configure"
+#line 9984 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12399,11 +12401,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12402: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12404: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12406: \$? = $ac_status" >&5
+   echo "$as_me:12408: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12503,11 +12505,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12506: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12508: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12510: \$? = $ac_status" >&5
+   echo "$as_me:12512: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14067,11 +14069,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14070: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14072: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14074: \$? = $ac_status" >&5
+   echo "$as_me:14076: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14171,11 +14173,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14174: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14176: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14178: \$? = $ac_status" >&5
+   echo "$as_me:14180: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16360,11 +16362,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16363: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16365: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16367: \$? = $ac_status" >&5
+   echo "$as_me:16369: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16650,11 +16652,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16653: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16655: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16657: \$? = $ac_status" >&5
+   echo "$as_me:16659: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16754,11 +16756,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16757: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16759: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16761: \$? = $ac_status" >&5
+   echo "$as_me:16763: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -20567,7 +20569,7 @@ echo $ECHO_N "checking for MPICH2 library and headers... $ECHO_C" >&6; }
     MPICH2_CC="$mpich2_dir/bin/mpicc"
 #    MPICH2_CC="$mpich2_dir/bin/mpicc -shlib"
     MPICH2_CPPFLAGS="-I$mpich2_dir/include"
-    MPICH2_LDFLAGS="-L$mpich2_dir/$abi_libdir -L$mpich2_dir/$alt_abi_libdir/libmpich.a"
+    MPICH2_LDFLAGS="-L$mpich2_dir/$abi_libdir -L$mpich2_dir/$abi_libdir/libmpich.a"
 #    MPICH2_LIBS="-lmpich"
     MPICH2_LIBS=""
     MPICH2_HEADER="$mpich2_dir/include/mpi.h"
@@ -20626,7 +20628,10 @@ eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
 	 test ! -s conftest.err
        } && test -s conftest$ac_exeext &&
        $as_test_x conftest$ac_exeext; then
-  found_mpich2=1
+  if ( (test -f $mpich2_dir/$abi_libdir/libmpich.a) ||
+             (test -f $mpich2_dir/$abi_libdir/shared/libmpich.so) ) ; then
+	    found_mpich2=1
+        fi
 
 
 else
@@ -20638,6 +20643,82 @@ fi
 
 rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
       conftest$ac_exeext conftest.$ac_ext
+
+    if test $found_mpich2 -eq 0; then
+
+       { echo "$as_me:$LINENO: checking for MPICH2 library (alt locations) and headers" >&5
+echo $ECHO_N "checking for MPICH2 library (alt locations) and headers... $ECHO_C" >&6; }
+
+       # Put -shlib into MPICH2_CC, since it is needed when building the
+       # tests, where $MPICH2_CC is used, and is not needed when building
+       # the MPI-related plugins, where $MPICH2_CC is not used.
+       MPICH2_CC="$mpich2_dir/bin/mpicc"
+#       MPICH2_CC="$mpich2_dir/bin/mpicc -shlib"
+       MPICH2_CPPFLAGS="-I$mpich2_dir/include"
+       MPICH2_LDFLAGS="-L$mpich2_dir/$alt_abi_libdir -L$mpich2_dir/$alt_abi_libdir/libmpich.a"
+#       MPICH2_LIBS="-lmpich"
+       MPICH2_LIBS=""
+       MPICH2_HEADER="$mpich2_dir/include/mpi.h"
+       MPICH2_DIR="$mpich2_dir"
+
+       CC="$MPICH2_CC"
+       CPPFLAGS="$CPPFLAGS $MPICH2_CPPFLAGS"
+       LDFLAGS="$LDFLAGS $MPICH2_LDFLAGS $MPICH_LIBS"
+
+       cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+   	  #include <mpi.h>
+
+int
+main ()
+{
+
+	  MPI_Initialized((int*)0);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  if ( (test -f $mpich2_dir/$alt_abi_libdir/libmpich.a) ||
+              (test -f $mpich2_dir/$alt_abi_libdir/shared/libmpich.so) ) ; then
+	     found_mpich2=1
+         fi
+
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+
+    fi
 
     CC=$mpich2_saved_CC
     CPPFLAGS=$mpich2_saved_CPPFLAGS
@@ -20712,7 +20793,7 @@ echo $ECHO_N "checking for MVAPICH library and headers... $ECHO_C" >&6; }
     # the MPI-related plugins, where $MVAPICH_CC is not used.
     MVAPICH_CC="$mvapich_dir/bin/mpicc -shlib"
     MVAPICH_CPPFLAGS="-I$mvapich_dir/include"
-    MVAPICH_LDFLAGS="-L$mvapich_dir/$abi_libdir -L$mvapich_dir/$alt_abi_libdir"
+    MVAPICH_LDFLAGS="-L$mvapich_dir/$abi_libdir"
     MVAPICH_LIBS="-lmpich -libverbs"
     MVAPICH_HEADER="$mvapich_dir/include/mpi.h"
     MVAPICH_DIR="$mvapich_dir"
@@ -20770,7 +20851,10 @@ eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
 	 test ! -s conftest.err
        } && test -s conftest$ac_exeext &&
        $as_test_x conftest$ac_exeext; then
-  found_mvapich=1
+  if ( (test -f $mvapich_dir/$abi_libdir/libmpich.a) ||
+             (test -f $mvapich_dir/$abi_libdir/shared/libmpich.so) ) ; then
+            found_mvapich=1
+        fi
 
 
 else
@@ -20782,6 +20866,79 @@ fi
 
 rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
       conftest$ac_exeext conftest.$ac_ext
+
+    if test $found_mvapich -eq 0; then
+       { echo "$as_me:$LINENO: checking for MVAPICH library (alt locations) and headers" >&5
+echo $ECHO_N "checking for MVAPICH library (alt locations) and headers... $ECHO_C" >&6; }
+
+       # Put -shlib into MVAPICH_CC, since it is needed when building the
+       # tests, where $MVAPICH_CC is used, and is not needed when building
+       # the MPI-related plugins, where $MVAPICH_CC is not used.
+       MVAPICH_CC="$mvapich_dir/bin/mpicc -shlib"
+       MVAPICH_CPPFLAGS="-I$mvapich_dir/include"
+       MVAPICH_LDFLAGS="-L$mvapich_dir/$alt_abi_libdir"
+       MVAPICH_LIBS="-lmpich -libverbs"
+       MVAPICH_HEADER="$mvapich_dir/include/mpi.h"
+       MVAPICH_DIR="$mvapich_dir"
+
+       CC="$MVAPICH_CC"
+       CPPFLAGS="$CPPFLAGS $MVAPICH_CPPFLAGS"
+       LDFLAGS="$LDFLAGS $MVAPICH_LIBS $MVAPICH_LDFLAGS $MVAPICH_LIBS"
+
+       cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+   	  #include <mpi.h>
+
+int
+main ()
+{
+
+	  MPI_Initialized((int*)0);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  if ( (test -f $mvapich_dir/$alt_abi_libdir/libmpich.a) ||
+              (test -f $mvapich_dir/$alt_abi_libdir/shared/libmpich.so) ) ; then
+	     found_mvapich=1
+         fi
+
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+
+    fi
 
     CC=$mvapich_saved_CC
     CPPFLAGS=$mvapich_saved_CPPFLAGS
@@ -20841,10 +20998,14 @@ else
 fi
 
 
-#    AC_ARG_WITH(mvapich2-driver,
-#		AC_HELP_STRING([--with-mvapich2-driver=NAME],
-#			       [MVAPICH2 driver name [ch-p4]]),
-#		mvapich2_driver=$withval, mvapich2_driver="")
+
+# Check whether --with-mvapich2-ofed was given.
+if test "${with_mvapich2_ofed+set}" = set; then
+  withval=$with_mvapich2_ofed; mvapich2_ofed_dir=$withval
+else
+  mvapich2_ofed_dir="/usr"
+fi
+
 
     { echo "$as_me:$LINENO: checking for MVAPICH2 library and headers" >&5
 echo $ECHO_N "checking for MVAPICH2 library and headers... $ECHO_C" >&6; }
@@ -20856,7 +21017,7 @@ echo $ECHO_N "checking for MVAPICH2 library and headers... $ECHO_C" >&6; }
     # the MPI-related plugins, where $MVAPICH2_CC is not used.
     MVAPICH2_CC="$mvapich2_dir/bin/mpicc -shlib"
     MVAPICH2_CPPFLAGS="-I$mvapich2_dir/include"
-    MVAPICH2_LDFLAGS="-L$mvapich2_dir/$abi_libdir -L$mvapich2_dir/$alt_abi_libdir"
+    MVAPICH2_LDFLAGS="-L$mvapich2_dir/$abi_libdir -L$mvapich2_ofed_dir/$abi_libdir"
     MVAPICH2_LIBS="-lmpich -libverbs -libcommon"
     MVAPICH2_HEADER="$mvapich2_dir/include/mpi.h"
     MVAPICH2_DIR="$mvapich2_dir"
@@ -20915,7 +21076,10 @@ eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
 	 test ! -s conftest.err
        } && test -s conftest$ac_exeext &&
        $as_test_x conftest$ac_exeext; then
-  found_mvapich2=1
+  if ( (test -f $mvapich2_dir/$abi_libdir/libmpich.a) ||
+             (test -f $mvapich2_dir/$abi_libdir/shared/libmpich.so) ) ; then
+	    found_mvapich2=1
+        fi
 
 
 else
@@ -20927,6 +21091,81 @@ fi
 
 rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
       conftest$ac_exeext conftest.$ac_ext
+
+    if test $found_mvapich2 -eq 0; then
+
+       { echo "$as_me:$LINENO: checking for MVAPICH2 library (alt locations) and headers" >&5
+echo $ECHO_N "checking for MVAPICH2 library (alt locations) and headers... $ECHO_C" >&6; }
+
+       # Put -shlib into MVAPICH2_CC, since it is needed when building the
+       # tests, where $MVAPICH2_CC is used, and is not needed when building
+       # the MPI-related plugins, where $MVAPICH2_CC is not used.
+       MVAPICH2_CC="$mvapich2_dir/bin/mpicc -shlib"
+       MVAPICH2_CPPFLAGS="-I$mvapich2_dir/include"
+       MVAPICH2_LDFLAGS="-L$mvapich2_dir/$alt_abi_libdir -L$mvapich2_ofed_dir/$alt_abi_libdir"
+       MVAPICH2_LIBS="-lmpich -libverbs -libcommon"
+       MVAPICH2_HEADER="$mvapich2_dir/include/mpi.h"
+       MVAPICH2_DIR="$mvapich2_dir"
+       MVAPICH2_NULL=""
+
+       CC="$MVAPICH2_CC"
+       CPPFLAGS="$CPPFLAGS $MVAPICH2_CPPFLAGS"
+       LDFLAGS="$LDFLAGS $MVAPICH2_LIBS $MVAPICH2_LDFLAGS $MVAPICH2_LIBS"
+
+       cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+   	  #include <mpi.h>
+
+int
+main ()
+{
+
+	  MPI_Initialized((int*)0);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  if ( (test -f $mvapich2_dir/$alt_abi_libdir/libmpich.a) ||
+               (test -f $mvapich2_dir/$alt_abi_libdir/shared/libmpich.so) ) ; then
+	    found_mvapich2=1
+          fi
+
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+
+    fi
 
     CC=$mvapich2_saved_CC
     CPPFLAGS=$mvapich2_saved_CPPFLAGS
